### ISSUE TITLE
I can't access multiplayer

### ISSUE THREAD

**Issue by Akul2010** [NowhereNotion/Minecraft-Mixin#1]
When I tried using Hypixel with this it gave me an error: java.lang.nullpointerexception

how do i fix this?

**Comment by drejbrando** [comment]
Did you launch it with Official Minecraft Launcher?

**Comment by Akul2010** [comment]
How do I do that? I'm just doing it through IntelliJ.

**Comment by drejbrando** [comment]
![image](https://github.com/NowhereNotion/Minecraft-Mixin/assets/94772414/55cc7aee-aec9-41bc-be3a-318767c12668)

![image](https://github.com/NowhereNotion/Minecraft-Mixin/assets/94772414/992afa07-98a5-4576-a49e-686229f2a9af)

![image](https://github.com/NowhereNotion/Minecraft-Mixin/assets/94772414/5df6491d-61c6-437c-a642-8dff986c1267)


please follow this guide @Akul2010

**Comment by Akul2010** [comment]
So I have to build whenever I want to test on multiplayer? Is there any other way or is this the only way?

**Comment by drejbrando** [comment]
yes this is the only way, srry for late comment

**Comment by Akul2010** [comment]
Oh, okay. Also I wanted to ask is there a tutorial on adding mods to it? Like Keystrokes maybe?

**Comment by drejbrando** [comment]
for those, you can use this Repo as a reference

https://github.com/Geuxy/pvp-mixin-base

if this repo helpful for you at some point, consider giving a star :)

**Comment by Akul2010** [comment]
> for those, you can use this Repo as a reference
> 
> https://github.com/Geuxy/pvp-mixin-base
> 
> if this repo helpful for you at some point, consider giving a star :)

Thank you, this is what I was looking for! Can you make some kind of mini-tutorial on adding mods?

**Comment by drejbrando** [comment]
i will make a tutorial video on these and ill let you know once it completed

**Comment by Akul2010** [comment]
Thank you, I appreciate it.
